apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
  namespace: kube-system
spec:
  extensions:
    helm:
      concurrencyLevel: 5
      repositories:
        - name: openebs-internal
          url: https://openebs.github.io/charts
        - name: metallb
          url: https://metallb.github.io/metallb
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
      charts:
        - name: openebs
          chartname: openebs-internal/openebs
          namespace: openebs
          order: 0
          timeout: 1h
          values: |
            localprovisioner:
              hostpathClass:
                enabled: true
                isDefaultClass: true
        - name: metallb
          chartname: metallb/metallb
          namespace: metallb
          order: 0
          timeout: 1h
        - name: cert-manager
          chartname: oci://quay.io/jetstack/charts/cert-manager
          version: "v1.18.2"
          namespace: cert-manager
          order: 1
          timeout: 1h
          values: |
            crds:
              enabled: true
        - name: trust-manager
          chartname: oci://quay.io/jetstack/charts/trust-manager
          namespace: cert-manager
          version: "v0.19.0"
          order: 1
          timeout: 1h
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          timeout: 1h
          order: 2
          values: |
            controller:
              ingressClassResource:
                default: true
